name: ros2wasm-builder
description: "Cross-compiles ROS 2 packages to WASM"

inputs:
  package:
    description: "Target package"
    type: string
    default: "test_pubsub"
    required: true
  debug_mode:
    description: "Debug mode"
    type: boolean
    default: false

runs:
  using: composite
  env:
      TARGET_PLATFORM: emscripten-32
      RMW_IMPLEMENTATION: rmw_wasm
      ROS_VERSION: 2
      ROS_DISTRO: humble
  steps:
    - name: Init simple action
      shell: bash -eux {0}
      run: |
        echo ${{ inputs.package }}
        echo ${ROS_DISTRO}
        echo "Env variable"
