name: ros2wasm-builder
description: "Cross-compiles ROS 2 packages to WASM"

inputs:
  package:
    description: "Target package"
    type: string
    default: "test_pubsub"
    required: true
  debug_mode:
    description: "Debug mode"
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Init simple action
      shell: bash -eux {0}
      run: |
        echo ${{ inputs.package }}
        echo ${ROS_DISTRO}
        echo "Env variable"
