name: test-action
on: 
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        run: ls -al

      - name: Use action
        uses: ./action.yml

      - name: After action
        run: echo "All done"

