name: test-action
on: 
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3

      # Simple checkout
      - name: Verify action
        shell: bash
        run: cat ./action.yml

      - name: Test action
        uses: ./
        with:
          package: "test_wasm"
          debug_mode: false

      - name: After action
        run: echo "All done"

