name: test-iron
on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify action
        shell: bash
        run: cat ./action.yml

      # Runs action and builds default package
      # Disabled until Iron patches are completed
      # - name: Test action
      #   uses: ./
      #   with:
      #     package: 'test_wasm'
      #     ros_distro: 'iron'
      #     debug_mode: false
