name: test-action
on: 
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Use action
        uses: actions/checkout@v3
        uses: ./.github/actions/builder/
        with:
          package: 'tst_pubsub'
          debug_mode: false

      - name: After action
        run: echo "All done"

